import uuid
from sqlalchemy import String, ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID
from pgvector.sqlalchemy import Vector
from app.models.base import Base

class DocumentChunk(Base):
    """
    Model representing a chunk of a document. Each chunk is associated with a specific document and contains:
    - `id`: Unical identifier for the chunk (UUID).
    - `document_id`: Foreign key linking the chunk to its parent document.
    - `text_content`: The original text of the chunk, which serves as context for LLMs.
    - `embedding`: A vector representation of the chunk's content, typically generated by an embedding model like Gemini's text-embedding-004 (768 dimensions).
    """
    __tablename__ = 'document_chunks'

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        unique=True
    )
    
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False
    )
    
    # text_content is the original text of the chunk, which serves as context for LLMs.
    # It's crucial for retrieval and question-answering tasks, as it provides the necessary information for the model to generate accurate responses.
    text_content: Mapped[str] = mapped_column(Text, nullable=False)
    
    # embedding is a vector representation of the chunk's content, typically generated by an embedding model like Gemini's text-embedding-004 (768 dimensions).
    embedding: Mapped[list[float]] = mapped_column(Vector(768), nullable=False)